[pytest]
addopts = --import-mode=importlib
pythonpath =
	schunk_fts_library
	schunk_fts_driver
norecursedirs = install build log .git __pycache__ *.egg-info test
filterwarnings =
	ignore:'asyncio\.get_event_loop_policy' is deprecated.*:Warning
	ignore:'asyncio\.set_event_loop_policy' is deprecated.*:Warning
